# Generated by Django 4.0.4 on 2022-05-06 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=100)),
                ('productId', models.CharField(max_length=100)),
                ('question', models.TextField(default='')),
                ('hasAcceptedAnswer', models.BooleanField(default=False)),
                ('time', models.FloatField()),
                ('upvotesCounter', models.IntegerField(default=0)),
                ('answersCounter', models.IntegerField(default=0)),
                ('hatesCounter', models.IntegerField(default=0)),
                ('isProduct', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='recommender.product')),
                ('price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
            bases=('recommender.product',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('mobile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommender.mobile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pros', models.TextField(default='')),
                ('cons', models.TextField(default='')),
                ('time', models.FloatField()),
                ('rating', models.IntegerField(default=0)),
                ('rating1', models.IntegerField(default=0)),
                ('rating2', models.IntegerField(default=0)),
                ('rating3', models.IntegerField(default=0)),
                ('rating4', models.IntegerField(default=0)),
                ('rating5', models.IntegerField(default=0)),
                ('likesCounter', models.IntegerField(default=0)),
                ('commentsCounter', models.IntegerField(default=0)),
                ('hatesCounter', models.IntegerField(default=0)),
                ('isProduct', models.BooleanField(default=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.mobile')),
            ],
        ),
    ]
