# Generated by Django 4.0.4 on 2022-05-20 12:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CReview',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pros', models.TextField(default='')),
                ('cons', models.TextField(default='')),
                ('time', models.FloatField()),
                ('rating', models.IntegerField(default=0)),
                ('likesCounter', models.IntegerField(default=0)),
                ('commentsCounter', models.IntegerField(default=0)),
                ('hatesCounter', models.IntegerField(default=0)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.company')),
            ],
        ),
        migrations.CreateModel(
            name='PReview',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('pros', models.TextField(default='')),
                ('cons', models.TextField(default='')),
                ('time', models.FloatField()),
                ('rating', models.IntegerField(default=0)),
                ('rating1', models.IntegerField(default=0)),
                ('rating2', models.IntegerField(default=0)),
                ('rating3', models.IntegerField(default=0)),
                ('rating4', models.IntegerField(default=0)),
                ('rating5', models.IntegerField(default=0)),
                ('rating6', models.IntegerField(default=0)),
                ('likesCounter', models.IntegerField(default=0)),
                ('commentsCounter', models.IntegerField(default=0)),
                ('hatesCounter', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AddField(
            model_name='user',
            name='CQ',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='user',
            name='CR',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='user',
            name='PQ',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='user',
            name='PR',
            field=models.IntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)]),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='price',
            field=models.FloatField(default=0.0, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AddField(
            model_name='preview',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.mobile'),
        ),
        migrations.AddField(
            model_name='preview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user'),
        ),
        migrations.AddField(
            model_name='creview',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user'),
        ),
    ]
