# Generated by Django 3.2.13 on 2022-05-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_auto_20220529_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prev_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.mobile')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
            options={
                'unique_together': {('userId', 'productId')},
            },
        ),
        migrations.CreateModel(
            name='Crev_Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.company')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
            options={
                'unique_together': {('userId', 'companyId')},
            },
        ),
    ]
