# Generated by Django 3.2.13 on 2022-05-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0004_crev_likes_prev_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='crev_likes',
            old_name='companyId',
            new_name='reviewId',
        ),
        migrations.RenameField(
            model_name='prev_likes',
            old_name='productId',
            new_name='reviewId',
        ),
        migrations.AlterUniqueTogether(
            name='crev_likes',
            unique_together={('userId', 'reviewId')},
        ),
        migrations.AlterUniqueTogether(
            name='prev_likes',
            unique_together={('userId', 'reviewId')},
        ),
    ]
