# Generated by Django 3.2.13 on 2022-06-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20220530_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cques_Upvotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CQuestion',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=100)),
                ('question', models.TextField(default='')),
                ('hasAcceptedAnswer', models.BooleanField(default=False)),
                ('time', models.FloatField()),
                ('upvotesCounter', models.IntegerField(default=0)),
                ('answersCounter', models.IntegerField(default=0)),
                ('hatesCounter', models.IntegerField(default=0)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.company')),
            ],
        ),
        migrations.CreateModel(
            name='Pques_Upvotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PQuestion',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=100)),
                ('productId', models.CharField(max_length=100)),
                ('question', models.TextField(default='')),
                ('hasAcceptedAnswer', models.BooleanField(default=False)),
                ('time', models.FloatField()),
                ('upvotesCounter', models.IntegerField(default=0)),
                ('answersCounter', models.IntegerField(default=0)),
                ('hatesCounter', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='pques_upvotes',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.pquestion'),
        ),
        migrations.AddField(
            model_name='pques_upvotes',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user'),
        ),
        migrations.AddField(
            model_name='cques_upvotes',
            name='questionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.cquestion'),
        ),
        migrations.AddField(
            model_name='cques_upvotes',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user'),
        ),
        migrations.AlterUniqueTogether(
            name='pques_upvotes',
            unique_together={('userId', 'questionId')},
        ),
        migrations.AlterUniqueTogether(
            name='cques_upvotes',
            unique_together={('userId', 'questionId')},
        ),
    ]
