# Generated by Django 3.2.13 on 2022-06-30 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0007_auto_20220628_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prev_Most_Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.preview')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
            options={
                'unique_together': {('userId', 'reviewId')},
            },
        ),
        migrations.CreateModel(
            name='Crev_Most_Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.creview')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
            options={
                'unique_together': {('userId', 'reviewId')},
            },
        ),
    ]
