# Generated by Django 3.2.13 on 2022-06-30 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_crev_most_liked_prev_most_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crev_most_liked',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommender.user'),
        ),
        migrations.AlterField(
            model_name='prev_most_liked',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommender.user'),
        ),
        migrations.AlterUniqueTogether(
            name='crev_most_liked',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='prev_most_liked',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='crev_most_liked',
            name='id',
        ),
        migrations.RemoveField(
            model_name='prev_most_liked',
            name='id',
        ),
    ]
