# Generated by Django 3.2.13 on 2022-06-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_auto_20220630_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crev_most_liked',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommender.user'),
        ),
        migrations.AlterField(
            model_name='prev_most_liked',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommender.user'),
        ),
    ]
