# Generated by Django 3.2.13 on 2022-07-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_auto_20220630_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cquestion',
            options={'ordering': ('-upvotesCounter', '-time')},
        ),
        migrations.AlterModelOptions(
            name='creview',
            options={'ordering': ('-likesCounter', '-time')},
        ),
        migrations.AlterModelOptions(
            name='pquestion',
            options={'ordering': ('-upvotesCounter', '-time')},
        ),
        migrations.AlterModelOptions(
            name='preview',
            options={'ordering': ('-likesCounter', '-time')},
        ),
        migrations.AddField(
            model_name='cquestion',
            name='company_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pquestion',
            name='product_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.CreateModel(
            name='CompanyOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.user')),
            ],
            options={
                'unique_together': {('user', 'company')},
            },
        ),
    ]
