# Generated by Django 3.2.13 on 2022-07-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0012_auto_20220707_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pquestion',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.product'),
        ),
        migrations.AlterField(
            model_name='preview',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.product'),
        ),
    ]
