# Generated by Django 3.2.13 on 2022-07-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0014_auto_20220707_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crev_most_liked',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommender.user'),
        ),
        migrations.AlterField(
            model_name='prev_most_liked',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommender.user'),
        ),
    ]
