# Author: Abdelrahman Hany
# Created on: 18-Feb-2022

name: Python application

on:
  push:
    branches: [ beta ]
    
jobs:
  buildAndRun:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f recommenderApi/requirements.txt ]; then pip install -r recommenderApi/requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        cd recommenderApi
        python manage.py runserver &
        PID=$!
        sleep 5
        kill $PID
    
  DeployToHeroku:
    needs: [buildAndRun]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Git deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: "e675c815-5b67-49cf-9a22-0c0cb98ae041"
        heroku_email: ${{ secrets.MAIL }}
        heroku_app_name: "urrevs-ai-dev"
        appdir: "recommenderApi"

  mergeToMain:
      needs: [DeployToHeroku]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Merge staging -> main
          uses: devmasx/merge-branch@v1.3.1
          with:
            type: now
            target_branch: main
            github_token: ${{ github.token }}
